baseURL: https://grbenjamin.github.io/
languageCode: en-us
title: fromskratch
theme: "PaperMod"

buildDrafts: false

params:
  env: production
  keywords: [Blog]
  author: Benjamín García Roqués
  DateFormat: "January 2, 2006"
  defaultTheme: auto

  assets:
    disableHLJS: true

  ShowBreadCrumbs: true # shows ex: home >> posts
  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: ["linkedin", "twitter", "reddit"]
  ShowCodeCopyButtons: true
  comments: true
  showtoc: true
  tocopen: false

  # 'suggest changes' button
  editPost:
    URL: "https://github.com/grbenjamin/blog/tree/main/content"
    Text: "Suggest changes"
    appendFilePath: true

  # home page
  homeInfoParams:
    Title: "building things, *fromskratch*."
    Content: |
      Heya! My name is Benjamín. I use this blog as a way of documenting everything I learn and build throughout the years,
      ranging from *[random nerdy stuff]*, to *[EVEN MORE RANDOM NERDY STUFF]*, with a focus on experimenting.
  
  socialIcons:
      - name: "GitHub"
        url: "https://github.com/grbenjamin"
      - name: "LinkedIn"
        url: "https://www.linkedin.com/in/benjamin-garcia-roques/"
      - name: "email"
        url: "mailto:benjamingarciaroques@gmail.com"
      - name: "rss"
        url: "https://grbenjamin.github.io/index.xml"
  
  # searching opts
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

enableInlineShortcodes: true
enableEmoji: true

menu:
  # nav bar
  main:
    - identifier: snippets
      name: snippets
      url: /snippets/ 
      weight: 10
    - identifier: about
      name: about
      url: /about/ 
      weight: 20
    - identifier: tags
      name: tags
      url: /tags/
      weight: 30
    - identifier: search
      name: search
      url: /search/ 
      weight: 40

markup:
  highlight:
    # noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: dracula

outputs:
  home:
    - HTML
    - RSS
    - JSON